from __future__ import annotations

import csv
import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_PAPER_DIR = ROOT / "input_papers" / "pdfs"
RECOMMENDED_PDF_COUNT = 20

SCRIPTS = [
    "build_manifest.py",
    "create_extract_templates.py",
    "validate_extracts.py",
    "synthesize_rules.py",
    "sync_skills_from_synthesis.py",
    "install_generated_skills.py",
    "run_basic_checks.py",
]

OUTLINE_REFS = [
    "outline_workflow.md",
    "section_templates.md",
    "problem_formulation_template.md",
    "method_section_template.md",
    "experiment_planning_template.md",
    "figure_table_planning.md",
    "reviewer_risk_checklist.md",
]

WRITING_REFS = [
    "writing_workflow.md",
    "section_writing_templates.md",
    "abstract_intro_gap_contribution_template.md",
    "problem_formulation_writing_template.md",
    "methodology_writing_template.md",
    "results_discussion_writing_template.md",
    "transition_and_coherence_rules.md",
    "overclaim_and_language_risk_checklist.md",
]


def has_frontmatter(path: Path) -> bool:
    if not path.exists():
        return False
    text = path.read_text(encoding="utf-8", errors="ignore")
    return bool(re.match(r"^---\s*\nname:\s*.+\ndescription:\s*.+?\n---", text, re.S))


def check(name: str, ok: bool) -> bool:
    print(f"[{'OK' if ok else 'FAIL'}] {name}")
    return ok


def resolve_paper_dir(value: str | None) -> Path:
    if not value:
        return DEFAULT_PAPER_DIR
    path = Path(value).expanduser()
    if not path.is_absolute():
        path = (ROOT / path).resolve()
    return path


def count_pdfs(path: Path) -> int:
    if not path.exists():
        return 0
    direct = list(path.glob("*.pdf"))
    return len(direct) if direct else len(list(path.rglob("*.pdf")))


def main(paper_dir: Path) -> int:
    failures = 0
    manifest_csv = ROOT / "data" / "paper_manifest.csv"
    manifest_xlsx = ROOT / "data" / "paper_manifest.xlsx"
    pdf_count = count_pdfs(paper_dir)

    checks = [
        (f"paper folder exists: {paper_dir}", paper_dir.exists()),
        ("PDF count checked", True),
        ("paper_manifest.csv exists", manifest_csv.exists()),
        ("paper_manifest.xlsx exists or can be generated by build_manifest.py", manifest_xlsx.exists() or manifest_csv.exists()),
        ("paper-corpus-analyzer SKILL.md frontmatter", has_frontmatter(ROOT / ".agents" / "skills" / "paper-corpus-analyzer" / "SKILL.md")),
        ("paper-skill-builder SKILL.md frontmatter", has_frontmatter(ROOT / ".agents" / "skills" / "paper-skill-builder" / "SKILL.md")),
        ("writing-paper-outline SKILL.md frontmatter", has_frontmatter(ROOT / ".agents" / "skills" / "writing-paper-outline" / "SKILL.md")),
        ("writing-paper SKILL.md frontmatter", has_frontmatter(ROOT / ".agents" / "skills" / "writing-paper" / "SKILL.md")),
        ("all scripts exist", all((ROOT / "scripts" / s).exists() for s in SCRIPTS)),
        ("outline references complete", all((ROOT / ".agents" / "skills" / "writing-paper-outline" / "references" / r).exists() for r in OUTLINE_REFS)),
        ("writing references complete", all((ROOT / ".agents" / "skills" / "writing-paper" / "references" / r).exists() for r in WRITING_REFS)),
        ("tests exist", (ROOT / "data" / "tests" / "paper_outline_test_prompts.md").exists() and (ROOT / "data" / "tests" / "paper_writing_test_prompts.md").exists()),
    ]

    if manifest_csv.exists():
        with manifest_csv.open("r", encoding="utf-8-sig", newline="") as f:
            reader = csv.DictReader(f)
            checks.append(("manifest has required include fields", "include_for_outline" in reader.fieldnames and "include_for_writing" in reader.fieldnames))

    for name, ok in checks:
        if not check(name, ok):
            failures += 1

    print("Basic check report complete.")
    print(f"- PDFs found: {pdf_count}")
    if pdf_count > RECOMMENDED_PDF_COUNT:
        print(
            f"- Recommendation: PDF count is above {RECOMMENDED_PDF_COUNT}. "
            "The workflow will continue, but skill quality is usually better with a focused set of the most relevant, highest-quality papers."
        )
    print(f"- Failures: {failures}")
    print("- PDF processing was not performed.")
    return 1 if failures else 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run basic checks for paper-skill-builder.")
    parser.add_argument("--paper-dir", default=None, help="Folder containing PDF files. Defaults to input_papers/pdfs.")
    args = parser.parse_args()
    raise SystemExit(main(resolve_paper_dir(args.paper_dir)))
